spring:
  application:
    name: restro-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: restro-auth-service
          uri: lb://restro-auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter

        - id: restro-restaurant-service
          uri: lb://restro-restaurant-service
          predicates:
            - Path=/api/v1/restaurant/**
          filters:
            - AuthFilter

        - id: restro-category-service
          uri: lb://restro-category-service
          predicates:
            - Path=/api/v1/category/**
          filters:
            - AuthFilter

        - id: qrops-product-service
          uri: lb://qrops-product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthFilter
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

restro:
  jwt:
    # JWT secret key
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"