INSERT INTO ROLES (ID, NAME) VALUES(1, 'SUPER_ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES(2, 'ADMIN');
INSERT INTO ROLES (ID, NAME) VALUES(3, 'OWNER');
INSERT INTO ROLES (ID, NAME) VALUES(4, 'USER');
