name: Build and Push Docker Images to Docker Hub

on:
  [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      # We can use a service container for the database if required, but it's optional.
      # Example: postgres:16 will be pulled from Docker Hub.
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: restro
          POSTGRES_USER: root
          POSTGRES_PASSWORD: sa

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build Docker images using Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push all Docker images to Docker Hub
        run: |
          # List the images built by docker-compose
          services=("restro-api-gateway-service" "restro-auth-service" "restro-eureka-discovery-service")
          for service in "${services[@]}"
          do
            docker tag $service:latest ${{ secrets.DOCKER_USERNAME }}/$service:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done